"""Build pages/gdpr-fines-analytics/analytics-data.js from the enforcement tracker's
analytics payload (the JSON in <script id="et-analytics">, saved as raw.json).

GDPR Articles are re-derived with the same rule the fine calculator uses: each
"Art. N" is kept only when the text up to the next "Art." names the Regulation
(GDPR / GPDR / GDRP / DSGVO / RGPD) or, once bracketed content is stripped, holds
no word of three or more letters. A word like that means another statute.
"""
import json, os, re, sys, collections, datetime

SRC = sys.argv[1] if len(sys.argv) > 1 else "raw.json"
OUT = sys.argv[2] if len(sys.argv) > 2 else "analytics-data.js"
rows = json.load(open(SRC, encoding="utf-8"))

ART = re.compile(r"\bArt(?:icle)?\.?\s*(\d{1,3})(?!\d)", re.I)
REG = re.compile(r"GDPR|GPDR|GDRP|DSGVO|RGPD", re.I)

def articles(text):
    text = text or ""
    ms = list(ART.finditer(text))
    out = []
    for i, m in enumerate(ms):
        tail = text[m.end(): ms[i + 1].start() if i + 1 < len(ms) else len(text)]
        keep = bool(REG.search(tail))
        if not keep:
            bare = re.sub(r"\([^)]*\)", " ", tail)
            keep = not re.search(r"[A-Za-zÀ-ɏ]{3,}", bare)
        n = int(m.group(1))
        if keep and 1 <= n <= 99 and n not in out:
            out.append(n)
    return sorted(out)

SECTOR_FIX = {"Accomodation and Hospitality": "Accommodation and Hospitality"}
TYPE_FIX = {
    "Insufficient involvement of data protection officer": "Insufficient involvement or appointment of a DPO",
    "Lack of appointment of data protection officer": "Insufficient involvement or appointment of a DPO",
}

# PII-01 (2026-10-07): natural persons named in the controller field are replaced
# with a role label from pseudonymise.json. Officials fined in a public role keep
# their names. Add new cases to the JSON, not here.
PSEUDONYMISE = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                           "pseudonymise.json"), encoding="utf-8"))

def controller(p):
    p = (p or "").strip()
    return PSEUDONYMISE.get(p, p)

def title_country(c):
    small = {"of", "and", "the"}
    return " ".join(w.lower() if (i and w.lower() in small) else w.capitalize() for i, w in enumerate(c.split()))

countries, authorities, sectors, types, controllers = {}, {}, {}, {}, {}
def idx(d, v):
    if v not in d: d[v] = len(d)
    return d[v]

packed, noart, stats = [], 0, collections.Counter()
for r in rows:
    arts = articles(r.get("r"))
    if not arts: noart += 1
    year = r.get("y")
    if year is None and r.get("d") and re.match(r"^\d{4}", r["d"]):
        year = int(r["d"][:4])
    packed.append([
        idx(countries, title_country(r.get("C") or r.get("c") or "Unknown")),
        idx(authorities, (r.get("a") or "Unknown").strip()),
        year,
        r.get("f"),
        idx(sectors, SECTOR_FIX.get(r.get("s"), r.get("s") or "Not assigned")),
        idx(types, TYPE_FIX.get(r.get("t"), r.get("t") or "Unknown")),
        arts,
        controller(r.get("p")),
    ])

def lst(d): return [k for k, _ in sorted(d.items(), key=lambda kv: kv[1])]
dates = sorted(r["d"] for r in rows if r.get("d") and len(r["d"]) == 10)
meta = {
    "cases": len(rows),
    "fined": sum(1 for r in rows if r.get("f") is not None),
    "total": sum(r.get("f") or 0 for r in rows),
    "latestDecision": dates[-1],
    "built": datetime.date.today().isoformat(),
    "noArticle": noart,
}
js = ("/* GDPR Fines Analytics data. Generated by build_analytics_data.py; do not edit by hand.\n"
      "   Source: the public GDPR enforcement tracker. Row layout:\n"
      "   [country, authority, year, fine EUR or null, sector, violation type, [GDPR Articles], controller] */\n"
      "var GFA_META = " + json.dumps(meta) + ";\n"
      "var GFA_COUNTRIES = " + json.dumps(lst(countries), ensure_ascii=False) + ";\n"
      "var GFA_AUTHORITIES = " + json.dumps(lst(authorities), ensure_ascii=False) + ";\n"
      "var GFA_SECTORS = " + json.dumps(lst(sectors), ensure_ascii=False) + ";\n"
      "var GFA_TYPES = " + json.dumps(lst(types), ensure_ascii=False) + ";\n"
      "var GFA_ROWS = [\n" + ",\n".join(json.dumps(p, ensure_ascii=False, separators=(",", ":")) for p in packed) + "\n];\n")
js = js.replace("\u2014", "-")
open(OUT, "w", encoding="utf-8", newline="\n").write(js)
print(meta, len(js.encode()))
