# Study layer for Part 1: Practical Privacy. Authored, not extracted.
# Key: topic number. Value: list of takeaway bullets.

TAKEAWAYS = {
 "1": [
  "The trigger is the technology, not the intent: any camera, tracker or monitoring tool is a personal-data activity from day one and needs an assessment before it is switched on.",
  "Transparency is the test a regulator applies first. Signage has four elements: controller, purpose, retention, how to exercise rights.",
  "Scope beats consent here. Narrow the collection (working hours only, no workstations, no public streets) rather than trying to paper over a wide scope with notices.",
  "Photography splits two ways: general consent for group shots, explicit consent for anyone who is the focal subject.",
  "Facial recognition and hidden cameras are the two bright lines: neither without a completed assessment and formal, documented sign-off.",
 ],
 "2": [
  "Offboarding protects two different parties at once: the leaver's personal privacy, and the organisation's records.",
  "The rule is asymmetric: delete personal content, leave business records. Those pull in opposite directions, which is why people get it wrong.",
  "Move business information into approved shared systems before access closes, not after. After is too late.",
  "The classic failure is exfiltration framed as convenience: forwarding to personal email, copying to a personal drive, keeping documents 'for reference'.",
  "If you cannot tell whether something is personal or business, ask before you act on it.",
 ],
 "3": [
  "Mailbox access is exceptional, never routine. Every instance needs its own justification and its own approval chain.",
  "Four situations can justify it: extended or unexpected leave, unresponsiveness threatening continuity, a legal or regulatory investigation, a departure without handover. Each still has to satisfy purpose limitation, fairness and proportionality.",
  "The five governance controls are least privilege, formal authorisation, logging, time-boxed elevation, and documentation.",
  "Prefer temporary, delegated access to the specific messages over full mailbox access. Scope is the control that does the most work.",
  "Tell the person afterwards, unless notification would compromise an investigation or legal process.",
 ],
 "4": [
  "One meeting can produce recordings, transcripts, captions, attendance reports, chat logs, polls and AI summaries. The organiser owns all of it.",
  "Ask the necessity question before enabling anything: would notes achieve the same goal?",
  "Match the tool to the meeting. Training and town halls are usually fine to record; HR matters, investigations and legal advice generally are not, or need sign-off first.",
  "For sensitive meetings, use a standalone invite rather than a channel meeting: channel meetings inherit permissions the discussion does not warrant.",
  "AI output is a draft. Review summaries and action items before they are relied on, and never paste meeting content into an unapproved tool.",
 ],
 "5": [
  "Location changes the environment, not the obligation. Three lenses still apply: privacy principles, security controls, records hygiene.",
  "The seven risk areas are networks, devices, information sharing, meetings and screen sharing, physical environment, printing and disposal, and test data.",
  "Share links, not files, and restrict to people with a genuine business need.",
  "Personal email is the single worst shortcut: it bypasses identity, access and logging controls in one move.",
  "Never build a personal workaround. Escalate and ask for a compliant path; formal exceptions need written justification, compensating controls and governance approval.",
 ],
 "6": [
  "Informality is the risk. A quiz feels casual; the data it collects is not, and the same platform, retention and transparency rules apply.",
  "Anonymous means unlinkable. If you can re-identify, it is not anonymous, and trying to re-identify is itself a breach of what you told people.",
  "Identity is sometimes necessary (a mandatory training quiz). When it is, the controls shift from anonymity to purpose limitation and access control.",
  "Never collect special categories in a pulse-check or feedback tool.",
  "Customer competitions carry more risk than internal surveys: approved vendor, published privacy statement, separate marketing consent, deletion on schedule, and a possible formal assessment in the planning timeline.",
 ],
 "7": [
  "People-data has a lifecycle of its own: recruitment, onboarding, performance, learning and talent, employee relations, collaboration, offboarding. Each stage has its own minimisation, access and retention expectation.",
  "The recurring failure across every stage is the same: data leaving the approved system into a personal folder, spreadsheet or mailbox.",
  "Recruitment questions stay tied to skills and role requirements. No age, family or health questions; no informal social-media checks.",
  "Performance records stay factual and role-related, in the approved HR system, visible only to authorised participants.",
  "Employee data must not go into external or unapproved AI tools, and must not be reused for a new purpose without a check.",
 ],
 "8": [
  "A rights request does not have to use legal language. 'Delete my information' and 'stop contacting me' both count.",
  "Speed is the whole point: statutory clocks start on receipt, so route it to the privacy team immediately instead of handling it yourself.",
  "Routine operational asks are not rights requests: updating account contact details, requesting a payslip, changing a billing email.",
  "Do not verify identity, investigate, or respond substantively on your own. A well-meant reply can undermine the formal process.",
  "Typical windows: one month under GDPR-style regimes (extendable by two more for complex cases, with notice inside the first month); around 30 calendar days in Australia; 20 working days in New Zealand. Confirm locally.",
 ],
 "9": [
  "Special categories are racial or ethnic origin, political opinions, religious or philosophical beliefs, trade union membership, genetic data, biometric data processed to uniquely identify a person, health, and sex life or sexual orientation.",
  "One of three gates has to genuinely apply: a clear legal obligation, explicit informed documented consent, or a necessary, defined and proportionate purpose. If none applies, do not collect it.",
  "Biometric data means physical or behavioural features used to identify or classify: faces, fingerprints, voice, keystrokes, gait.",
  "A project involves biometrics if it scans a face, voice or behaviour, compares features to a stored record, or uses features to decide about identity, access, attendance or classification.",
  "Biometrics are never assessment-optional: stop, complete a formal assessment, show why nothing less intrusive works, and do not sign a vendor contract before privacy review completes.",
 ],
 "10": [
  "Consent only works where refusal is genuinely free of consequence. Payroll, security, safety checks, performance management and access control do not meet that test.",
  "Valid consent has four properties: informed, voluntary, specific and current, and given by someone with capacity.",
  "A privacy notice is not consent. A notice informs; consent grants permission.",
  "Never rely on silence, pre-ticked boxes or inaction, and never bundle unrelated purposes into one request.",
  "Withdrawal must be as easy as giving it, and honoured promptly. If you cannot track withdrawal, you cannot use consent.",
 ],
 "11": [
  "Availability is not a justification. Data collected for one purpose cannot be reused for another just because it is there.",
  "Confirm the original purpose first. If the new use does not clearly fit what people were told, it is secondary use, even if the shift is small.",
  "A new purpose may need a new notice, new consent, a new lawful basis, a fresh assessment, or added safeguards. Do not assume the old ones stretch.",
  "Seven escalation triggers: material purpose change, sensitive or children's data, an automated decision affecting someone, a new vendor, a cross-border move, anonymisation not possible, or an unassessed use.",
  "Document the decision: business justification, compatibility assessment, lawful basis, consent status, review outcome, approval.",
 ],
 "12": [
  "The core rule has no exceptions in normal conditions: never hand data to an external requester directly. Escalate to privacy and legal.",
  "External requests are not rights requests. Different process, different risk, different approver.",
  "Gather the facts before escalating: requester identity and official contact details, request type, legal basis, precise scope, data type, transfer requirements.",
  "Minimise every disclosure to a specific camera, timeframe or incident. Never a blanket handover, never an ordinary email attachment.",
  "Emergencies (threat to life, medical emergency, missing person, disaster, court order) can justify disclosure, but still require verification, minimisation, documentation and immediate notification to privacy afterwards. Family members and commercial third parties get referred to authorities, not answered.",
 ],
 "13": [
  "The tooling changes quickly; the principles do not. Check the current internal AI policy rather than relying on general principle alone.",
  "Keep a human in the loop for any decision that meaningfully affects a person, and treat AI output as a draft rather than an answer.",
  "Verify facts, numbers and anything feeding a decision about a person before relying on it.",
  "Only approved tools touch company or personal data. Never paste confidential, personal or sensitive information into a public tool.",
  "Assess new personalisation, profiling or automated-decision features for fairness and bias before launch, not after.",
 ],
 "14": [
  "Nobody engages a regulator independently. Every contact routes to privacy and legal immediately.",
  "The rule extends to threatened contact: a customer threatening escalation, or a supplier signalling regulator involvement, both trigger it.",
  "Nothing goes out externally without approval: emails, incident reports, data extracts, screenshots, logs, investigation notes.",
  "For an unannounced inspection there are four roles: reception notifies leadership, leadership attends and calls privacy, privacy guides and records, everyone else refers and says nothing about internal process.",
  "Politeness is not cooperation with the substance. Stay professional, hand over nothing before authorised staff arrive.",
 ],
 "15": [
  "Technically possible is not legally permitted. Privacy comes before launch, not after.",
  "Five triggers for formal review: a new digital asset, new functionality, a technology change, a change in what is processed, or live personal data used in testing.",
  "The review confirms five things: lawful basis and consent mechanism, accurate current notices, retention and rights handling, vendor contract terms, and secure hosting with access control, encryption and logging.",
  "The most common failure is tags firing before consent. Disable, fix the consent configuration, retest.",
  "Relaunching an old site, or reusing an outdated notice, counts as a new launch for review purposes.",
 ],
 "16": [
  "Speed beats certainty. Report on suspicion; do not wait for facts, and do not investigate alone.",
  "Regulator notification windows are commonly measured in hours from the moment the organisation becomes aware, so every hour of internal delay is spent from the legal budget.",
  "Five common incident types: email errors, system access issues, physical security, cyber threats, improper disposal.",
  "The lifecycle is intake, investigation and containment, assess and decide, notify. Containment can start before the assessment finishes.",
  "Preserve evidence, answer follow-up questions, and never handle an incident independently.",
 ],
 "17": [
  "Risk grows in three specific ways: oversharing, keeping too long, storing in the wrong place. The lifecycle is create, store, use, share, retain and archive, delete.",
  "Three storage tiers do most of the work: personal working space for drafts, collaboration space for live team work, structured storage for final managed records.",
  "Four classification labels: public, internal, confidential, highly confidential. When in doubt, choose the more restrictive one and ask.",
  "The hidden-content check is the practical skill: hidden tabs and rows, filters that hide rather than remove, pivot caches, comments and tracked changes, embedded formulas and links. Inspect before sending.",
  "Backups quietly extend retention past the approved period, and auto-deleting chat history is not a record. Both are places the retention schedule silently fails.",
  "Never purge anything that may be under legal, tax, audit or regulatory hold, even when the retention rule says delete.",
 ],
 "18": [
  "Marketing is defined by primary purpose, not by channel or by whether the recipient is already a customer. Adding a promotional link to an operational message converts the whole message.",
  "Consent for marketing is channel-specific: email consent does not cover SMS. Record the timestamp, the exact wording shown, the channel and the source.",
  "Every marketing message needs a working, free, promptly processed unsubscribe. Australia sets a five business day deadline as an example of a hard one.",
  "Mislabelling marketing as a service communication is one of the most commonly enforced violations, and the cautionary example is a roughly AUD 700,000 fine for 370,000+ emails with no working unsubscribe.",
  "Profiling, children's data and third-party broker data are the three areas that always need privacy involvement before launch.",
  "The vendor does not carry your compliance. The sending organisation stays accountable for templates, governance and approvals.",
 ],
}

SELFTEST = [
 ("A team wants to install cameras covering the staff car park and the row of desks nearest the entrance. Which part of that is a problem, and why?",
  "The desks. Pointing cameras at individual workstations is on the never list, because continuous monitoring of identified people at work is disproportionate to almost any stated purpose. The car park can be justified with a narrow purpose, signage naming controller, purpose, retention and rights, and a completed assessment."),
 ("Name the four things signage must tell people.",
  "Who the controller is, the purpose, the retention period, and how to exercise rights or get more information."),
 ("A leaver deletes their personal photos and also deletes three years of project emails. What did they get wrong?",
  "The project emails. Offboarding deletes personal content only; business records must stay available for legal, retention and operational purposes."),
 ("An account manager is unreachable and a customer needs a document in their inbox. What is the correct shape of the response?",
  "Document the justification, get privacy sign-off, grant temporary time-boxed delegated access to the specific relevant messages rather than the whole mailbox, log the access, and remove it when done. Tell the person afterwards unless that would compromise an investigation."),
 ("Why prefer a standalone meeting invite over a channel meeting for a sensitive discussion?",
  "Channel meetings inherit the channel's broader permissions, so the recording, transcript and chat become visible to a wider group than the discussion warrants. A standalone invite has a defined attendee list."),
 ("Which three lenses apply to remote work?",
  "Privacy principles (fairness, purpose limitation, minimisation), security controls (device management, access, monitoring), and records hygiene (approved storage, retention, timely deletion)."),
 ("An employee survey collects no names but does record IP addresses and department for a team of four. Is it anonymous?",
  "No. With a team that small, department plus IP is realistically re-identifiable, so it should be treated as identified data, with the transparency and access controls that follow, or the identifiers should be dropped."),
 ("Which of these is not a rights request: 'send me a copy of my data', 'change my billing email', 'stop contacting me', 'who did you share my data with'?",
  "'Change my billing email.' That is a routine operational request, even though it involves personal data."),
 ("What is the GDPR-style response window, and what is the condition on extending it?",
  "One month, extendable by up to two further months for complex cases, provided the requester is told about the extension within the first month."),
 ("List the three gates, any one of which can permit special-category processing.",
  "A clear legal obligation; explicit, informed, documented consent; or a purpose that is necessary, defined and proportionate. If none applies, do not collect it."),
 ("What makes a project a biometrics project?",
  "It scans a face, voice or behaviour; or compares physical features against a stored record; or uses those features to decide about identity, access, attendance or classification."),
 ("Give two everyday activities where consent is the wrong lawful basis, and say why.",
  "Any two of payroll, IT security, safety checks, performance management, access control, mandatory compliance activity. Refusal carries a negative work consequence, so the choice is not free, which is what consent requires."),
 ("What is the difference between a privacy notice and consent?",
  "A notice informs; consent grants permission. A notice can never be treated as consent, and consent without a notice fails the informed limb."),
 ("A logistics team wants to reuse delivery data for a marketing model. Name three things this triggers.",
  "It is secondary use, so: confirm the original purpose and run a compatibility assessment; check whether a new notice, consent or lawful basis is needed; and document the decision. Prefer pseudonymised data, and escalate if a new vendor or cross-border move is involved."),
 ("A police officer calls and asks for CCTV footage of an incident. What do you do?",
  "Do not release anything. Collect the requester's name, organisation, badge or registration number, the legal basis, the precise scope (date, time, camera) and any transfer requirement, then escalate to privacy and legal, who decide whether and how to disclose."),
 ("What is the minimum you must do before relying on an AI-generated meeting summary or analysis?",
  "Review it for accuracy, validate the decisions and actions it records, remove unnecessary personal data, and correct errors. Treat it as a draft, never as an official record on its own."),
 ("Five triggers require a formal review of a website or digital product. Name three.",
  "Any three of: launching something new; adding functionality such as forms, cookies, pixels or analytics; changing the underlying technology, host or vendor; changing what is processed (new data, new markets, new AI, new automation); or using live personal data in testing or pre-production."),
 ("Why is 'I will report it once I have checked what happened' the wrong instinct after a suspected breach?",
  "Notification clocks run from organisational awareness and are commonly measured in hours. Internal verification time is spent out of the legal budget, and containment can start in parallel anyway. The rule is report on suspicion."),
 ("Name three places where a retention schedule silently fails.",
  "Backups that extend retention past the approved period; exports and extracts into spreadsheets and email; archived or decommissioned system instances. Auto-deleting chat also fails the other way, destroying something that should have been a record."),
 ("A renewal reminder email includes a 20% discount code for a different product. What has it become, and what does it now need?",
  "Marketing. It now needs valid channel-specific opt-in consent, a working free unsubscribe, truthful classification, and the campaign checks before sending. Hiding promotional content inside an operational message is one of the most commonly enforced violations."),
]
