# Study layer for Part 2: Practical AI Act Advice. Authored, not extracted.

TAKEAWAYS = {
 "1": [
  "The Act is horizontal: it sits underneath every industry rather than inside one. An internal ops tool is as in scope as a foundation model.",
  "Four operational roles carry different duties: provider, deployer, importer, distributor, with authorised representatives and product manufacturers appearing where relevant. Most weight sits on providers.",
  "Role is not fixed. Under Article 25 a deployer, distributor or importer becomes the provider of a high-risk system if it puts its name on one, substantially modifies one, or changes a system's purpose so that it becomes high-risk. Rebranding a low-risk tool does not do it; repurposing can.",
  "Three independent territorial triggers: placing a system or model on the EU market from anywhere; being an EU-established deployer; or being anywhere in the world when your AI's output is used in the EU. The third is the one non-EU organisations miss.",
  "The open-source system exclusion stops the moment the system is placed on the market as prohibited, high-risk or transparency-triggering; open-source GPAI models have their own narrower relief (Section 6). Treat 'it is open source' as a question, not an answer.",
 ],
 "2": [
  "This is the one tier with no proportionality dial. No mitigation brings a prohibited practice back into bounds, and exposure runs to 7% of global turnover.",
  "Screen against this list first, before any other compliance work. Nothing downstream fixes a practice banned at the root.",
  "The ten categories, eight original and two added by Regulation (EU) 2026/1744 from 2 December 2026: subliminal or deceptive manipulation; exploiting vulnerability (age, disability, socioeconomic situation); social scoring; individual predictive policing based purely on profiling; emotion inference at work and in education; untargeted facial-image scraping; biometric categorisation inferring protected traits; real-time remote biometric identification in public by law enforcement; generating non-consensual intimate imagery; generating child sexual abuse material.",
  "Four of the original eight carry exclusions: predictive policing that supports a human assessment on objective facts; biometric categorisation that labels lawful datasets or is used in law enforcement; emotion inference for medical or safety purposes; and real-time biometric identification for victim and missing-person searches, imminent threats to life, or Annex II suspects, with prior judicial or administrative authorisation (24-hour urgency route).",
  "The realistic risk is drift, not intent: a well-meant engagement or wellness feature crossing into a banned category without anyone naming it that way.",
 ],
 "3": [
  "Two independent routes to high-risk. Run both: a system can clear the product-safety route and still land in Annex III, or the reverse.",
  "Route one is the Annex III use-case list: biometrics; critical infrastructure; education and vocational training; employment and worker management; essential services and benefits; law enforcement; migration, asylum and border control; judicial and democratic processes.",
  "Route two needs two conditions: a product or safety component covered by an Annex I law, and a third-party conformity assessment under that law. Section A (toys, lifts, radio, pressure, cableways, PPE, gas appliances, medical devices, recreational craft, explosive atmospheres) checks the AI rules inside the product assessment; Section B (vehicles, aviation, marine, rail and, since the Omnibus, machinery) applies only Article 6(1) and the final provisions.",
  "The carve-out has four situations only (narrow procedural task; improving a completed human activity; detecting decision patterns without replacing the human assessment; preparatory task) and one override: profiling of natural persons is always high-risk. Document the assessment before market placement, not just the conclusion.",
  "Classification is not permanent. Repurposing a tool into, say, a hiring decision can cross the line with no code change.",
  "Annex III high-risk systems (and carve-out exemptions) are registered in the EU database before use; critical infrastructure registers nationally, law enforcement and migration entries are non-public, and Annex I product systems are not in it. From 2 December 2027; the database was not yet open in September 2026.",
 ],
 "4": [
  "The provider obligation set is engineered in, not bolted on: risk management and data governance start at design time.",
  "The twelve items: risk management system; data and data governance (with Article 4a for special-category data used to detect bias); technical documentation; automatic logging (kept at least six months); instructions for use; human oversight by design; accuracy, robustness and cybersecurity; quality management system; accessibility; conformity assessment; registration; regulatory cooperation. Around them: corrective action, CE marking, post-market monitoring, serious-incident reporting and, for non-EU providers, an authorised representative.",
  "Technical documentation is the file a regulator or auditor asks for first: description, performance metrics, test results, data lineage, conformity declaration.",
  "Human oversight by design means a human can meaningfully interpret and explain what the system is doing, not merely switch it off.",
  "Stage-gate the twelve: some at design, some pre-launch, some ongoing, each with a named owner. Documentation and quality management are the two that fall between engineering and legal.",
 ],
 "5": [
  "Most organisations are deployers, which makes vendor selection a compliance decision rather than a procurement one.",
  "The eight deployer duties: follow the instructions for use; assign competent human oversight; ensure input data quality where you control it; monitor, and where a risk appears inform the provider and the authority and suspend use, reporting serious incidents to the provider first; keep the logs at least six months; be transparent to workers' representatives, affected employees and affected individuals; cooperate with regulators; complete a DPIA where one applies.",
  "Deviating from the documented use is the quickest way to take on provider-level exposure, but the deployer duties are its own whether or not the instructions were followed; a provider's breach is not automatically the deployer's.",
  "Oversight must be assigned to someone with the competence, training and authority to exercise it. A sign-off from someone who does not understand the system does not satisfy the obligation.",
  "A fundamental rights impact assessment is not universal. It applies to public-law bodies, private providers of public services, and deployers of two Annex III use cases: creditworthiness evaluation or credit scoring of natural persons (excluding fraud detection) and life and health insurance risk assessment and pricing. It covers only Annex III systems (not critical infrastructure), records processes, period, people affected, harms, oversight and complaint routes, is notified to the market surveillance authority, may cross-reference a DPIA, and applies from 2 December 2027.",
  "Importers and distributors have a narrower but non-negotiable duty: verify conformity via the Declaration of Conformity and CE marking rather than taking the provider's word.",
 ],
 "6": [
  "GPAI is a separate lane from high-risk systems. A model carries its own obligations regardless of what it ends up inside.",
  "The four baseline obligations: publish a detailed training-data summary; maintain an EU copyright compliance policy; keep technical documentation current; document capabilities and limitations for downstream providers.",
  "Open-source models with public weights are relieved of the two documentation duties only; the copyright policy and training summary always apply, and the relief disappears if the model is classified as systemic-risk.",
  "Systemic risk is set by high-impact capability, measured primarily by cumulative training compute, or by Commission designation. The headline proxy is 10^25 floating-point operations of cumulative training compute, explicitly a moving target, and crossing it is a presumption: notify the Commission within two weeks, argue against it if you can.",
  "Systemic risk adds five duties: notify the Commission; run model evaluation and adversarial testing; maintain adequate cybersecurity; report serious incidents; assess and mitigate key systemic risks.",
  "GPAI obligations applied from 2 August 2025, twelve months after entry into force; the Commission's fining powers over GPAI providers from 2 August 2026; pre-existing models must comply by 2 August 2027. Codes of Practice plus AI Office templates are the recognised route to demonstrating compliance.",
 ],
 "7": [
  "There is no single checklist. Requirements are layered at use case, model, system and organisation level, and shift as your portfolio and roles shift.",
  "The working sequence is five steps: screen out prohibited practices; inventory and track high-risk AI; run a gap analysis; register what needs registering; roll out AI literacy training.",
  "Prohibited-practice screening is the first gate, not a later one.",
  "Conformity assessment happens before market placement or putting into service, and the applicable procedure varies by system type. There is no universal form.",
  "Limited-risk transparency is a separate, lighter tier with four parts: tell people they are interacting with AI; mark synthetic output machine-readably; inform people exposed to emotion recognition or biometric categorisation; disclose deep fakes and AI-written public-interest text unless it is under editorial responsibility.",
  "The tiers are not mutually exclusive. A high-risk recruitment tool with a chatbot front end owes both sets of duties, and a GPAI model can sit inside any of them. Never answer 'what applies to us' in the abstract.",
 ],
 "8": [
  "Enforcement is distributed, not centralised: each member state appoints at least one market surveillance authority and one notifying authority, with one designated as the primary contact point.",
  "Two EU-level bodies: the European AI Office inside the Commission, which enforces GPAI rules and develops Codes of Practice, and the European AI Board, one representative per member state, which harmonises implementation.",
  "The dates that matter: published 12 July 2024; in force 1 August 2024; prohibited practices applicable 2 February 2025; GPAI provider obligations, governance, penalties and the authority-appointment deadline 2 August 2025; transparency, national market surveillance and the Commission's GPAI fines 2 August 2026; the two new prohibitions 2 December 2026; Annex III high-risk obligations 2 December 2027; Annex I product-embedded systems 2 August 2028. The last two were moved by Regulation (EU) 2026/1744, in force 27 July 2026.",
  "Three penalty tiers: 7% of global turnover or EUR 35m for prohibited practices; 3% or EUR 15m for operator, notified-body and Article 50 obligations (and, under Article 101, for GPAI providers); 1% or EUR 7.5m for supplying incorrect or misleading information to regulators. Whichever is higher, except for SMEs, startups and small mid-caps, where the lower amount applies.",
  "Member states set their own regimes within those ceilings; the SME rule is a hard cap (whichever is lower), not just a call for proportionality.",
 ],
 "9": [
  "Point compliance does not survive portfolio growth. The goal of a program is that new use cases get evaluated the same way every time.",
  "The ten foundations: policy and standards framework; risk management framework; live AI inventory; governance board with real decision rights; AI-specific third-party risk management; regulatory horizon-scanning; metrics, assurance and audit; education and training; technical tooling and guardrails; alignment with existing digital governance functions.",
  "Start with the inventory. You cannot govern what you have not found, and shadow AI adoption is usually larger than leadership assumes.",
  "A governance board without authority to block a launch is an advisory committee, not governance.",
  "General vendor security review is not AI third-party risk management, and governance that lives only in policy documents erodes under delivery pressure.",
  "Extend existing structures (risk committees, vendor review, data governance) rather than building a parallel silo.",
 ],
 "10": [
  "The value of a standard intake form is comparability. Ten identical questions across the portfolio beat ten bespoke interviews.",
  "The ten questions: purpose; value; data rights; geography; model choice; third-party dependencies; output; human oversight; impact of failure; ongoing monitoring.",
  "Two questions carry most of the weight: whether you actually have the right to use the data, and whether the person overseeing can genuinely verify and act rather than rubber-stamp.",
  "Geography is asked three ways: where developed, where made available, where used. Those can be three different answers and three different obligation sets.",
  "Route answers that reveal high-risk classification, prohibited-practice overlap or weak oversight to a mandatory second review before build work proceeds.",
 ],
 "11": [
  "Procurement is where most downstream risk is decided: a deployer cannot meet its own duties on a system the provider has not documented, even though a provider's breach is not automatically the deployer's.",
  "The ten questions: their governance; training data and its legal basis; whether they use your data to train; litigation exposure; IP indemnity; sub-dependencies; output ownership; documentation; demonstrable regulatory compliance; support.",
  "Three of the ten belong in the contract, not in an email: IP indemnity, data-use rights, output ownership.",
  "Get all ten answered in writing before signature. After signature you have lost the leverage.",
  "A vendor who cannot answer the compliance and documentation questions with specifics is itself the risk signal, however good the demo was.",
 ],
 "12": [
  "AI literacy is a legal requirement, not a training nicety: Article 4, applicable since 2 February 2025, reworded by Regulation (EU) 2026/1744 to require measures that support the development of AI literacy, with no sufficient level mandated.",
  "It also props up another obligation: human oversight of high-risk systems must sit with competent, trained people, which is meaningless without a literacy program behind it.",
  "Four layers: governance fundamentals for everyone; generative AI enablement; role-based training; system-specific operational training.",
  "Layer two works best when it is inspirational and interactive rather than compliance-flavoured. Layer four is the one that serves the Article 26(2) competence requirement for anyone operating a high-risk system.",
  "Article 4 prescribes no curriculum or number of layers; the four layers are a recommended design. What is needed is evidence of measures that fit audience and risk exposure, and layer four should be tied to the high-risk inventory rather than rolled out organisation-wide.",
 ],
 "13": [
  "Two separate questions sit side by side: does your AI use infringe someone's copyright, and is your AI output protectable at all.",
  "Exposure appears at five points in the lifecycle: training, fine-tuning, retrieval-augmented generation, prompts and inputs, and inference and outputs.",
  "Output protectability turns on human authorship. Purely AI-generated content with no meaningful human creative input generally is not protectable; AI-assisted work often is. In the US, typing a prompt alone is not enough; the Supreme Court declined to review Thaler v Perlmutter in March 2026, which leaves the D.C. Circuit ruling standing without endorsing it.",
  "Applicable rules are generally determined by where the copying took place, and the jurisdictions diverge sharply: US fair use worked out case by case; EU copyright law applies plus a training-data transparency duty and two text-and-data-mining exceptions, the broader one subject to rightsholder opt-out; the UK dropped its opt-out proposal and endorsed no option in its March 2026 report; Japan permissive but conditional; China comparatively strict with no explicit exemption and mandatory labelling since September 2025.",
  "Three US merits rulings so far: Bartz v Anthropic (training on lawfully acquired books fair use, pirated library not, USD 1.5bn settlement approved July 2026), Kadrey v Meta (fair use on narrow facts), Thomson Reuters v Ross (no fair use, Third Circuit pending). Germany's Munich court held memorisation in the model to be reproduction outside the TDM exception, for lyrics in GEMA v OpenAI and for six musical works in GEMA v Suno (not yet final). The four US fair-use factors: purpose and character of the use, nature of the work, amount and substantiality used, and effect on the market for the original.",
  "The six mitigations: license deliberately and prove provenance; negotiate IP indemnity covering outputs; test for memorisation and output reproduction; track data lineage as a standing part of risk assessment; train employees on prompting and uploads; and meet the GPAI training-data transparency obligation, now backed by Commission fining powers.",
 ],
}

SELFTEST = [
 ("A US company with no EU office sells a SaaS product with an embedded chatbot to EU customers. In scope or not, and on which trigger?",
  "In scope, as a provider. Selling to EU customers places the system on the EU market (first trigger); even without that, the third trigger catches any provider or deployer whose AI output is used within the EU, regardless of establishment."),
 ("You buy a third-party model, fine-tune it heavily and ship it under your own brand. What changed?",
  "Your role, possibly twice. Fine-tuning a general-purpose model makes you the provider of the modified model, for the modification. If the system is high-risk, putting your name on it or substantially modifying it makes you its provider under Article 25, with the full provider obligation set; a low-risk tool rebranded stays low-risk unless you change its purpose."),
 ("Name the four roles the Act assigns and say which carries the most weight.",
  "Provider, deployer, importer, distributor, with authorised representatives and product manufacturers where relevant. Most of the Act's weight sits on providers."),
 ("List four of the ten prohibited practices.",
  "Any four of: subliminal or deceptive manipulation causing significant harm; exploiting vulnerability by age, disability or socioeconomic situation; social scoring; individual predictive policing based purely on profiling; emotion inference in the workplace or education; untargeted scraping of facial images; biometric categorisation inferring protected traits; real-time remote biometric identification in public by law enforcement; and, from 2 December 2026, generating non-consensual intimate imagery or child sexual abuse material."),
 ("An employer proposes webcam emotion analysis in meetings to measure engagement. What is the analysis, and what is the fix?",
  "It falls inside the workplace emotion-recognition prohibition, and the medical or safety carve-out does not apply to a productivity feature. There is no mitigation that brings it back into bounds. The only fix is not building it."),
 ("What are the two routes to high-risk classification, and how do you test them?",
  "The Annex III use-case list (with the Article 6(3) carve-out and its profiling override), and being a product or safety component covered by an Annex I law that also requires a third-party conformity assessment. Run both independently; clearing one does not clear the other."),
 ("Four of the Annex III categories, please.",
  "Any four of: biometrics; critical infrastructure; education and vocational training; employment and worker management; essential services and benefits; law enforcement; migration, asylum and border control; judicial and democratic processes."),
 ("You conclude an Annex III system is not high-risk because it performs a narrow task. What must you do?",
  "Check the task is one of the four Article 6(3) situations and that the system does not profile natural persons, document the assessment before placing it on the market, and register the system under Article 49(2). The documented rationale is what you defend the conclusion with later."),
 ("Name six of the twelve provider obligations for high-risk systems.",
  "Any six of: risk management system; data and data governance; technical documentation; automatic logging; instructions for use; human oversight by design; accuracy, robustness and cybersecurity; quality management system; accessibility; conformity assessment; registration; regulatory cooperation."),
 ("Which three categories of deployer must complete a fundamental rights impact assessment?",
  "Bodies governed by public law, private entities providing public services, and deployers of two Annex III use cases: creditworthiness evaluation or credit scoring of natural persons (fraud detection excluded) and life and health insurance risk assessment and pricing. In every case only for Annex III high-risk systems, excluding critical infrastructure."),
 ("A bank deploys a third-party AI that scores the creditworthiness of applicants. List what the bank owes as deployer.",
  "Obtain and follow the provider's instructions for use; assign competent human oversight of the credit decisions; complete and notify a fundamental rights impact assessment, since creditworthiness evaluation is a triggering use case; tell applicants a high-risk system is used; keep the logs at least six months; monitor, suspend use if a risk appears, and report serious incidents to the provider first. The vendor's own compliance work does not discharge any of it."),
 ("What are the four baseline GPAI provider obligations, and when do they stop applying?",
  "Publish a detailed training-data summary; maintain an EU copyright compliance policy; keep technical documentation current; document capabilities and limitations for downstream providers. Open-source models with public weights are relieved of the two documentation duties only; the copyright policy and training summary never stop applying, and systemic-risk classification cancels the relief."),
 ("What does 10^25 floating-point operations mean in this context, and why is it not a permanent number?",
  "Cumulative training compute above that level is the Act's main proxy for high-impact capability and therefore systemic risk: a presumption the provider must notify within two weeks and may rebut. It is explicitly designed to be reviewed and adjusted as the technology develops."),
 ("Give the five-step working compliance sequence.",
  "Screen out prohibited practices; inventory and track high-risk AI; run a gap analysis against the full requirement set; register high-risk systems in the EU database; roll out AI literacy training."),
 ("The four Article 50 transparency obligations.",
  "Providers must design systems so people know they are interacting with AI; providers must mark synthetic output machine-readably; deployers of emotion recognition or biometric categorisation must inform the people exposed; deployers must disclose deep fakes and AI-written public-interest text unless it is under editorial responsibility."),
 ("Match the dates: prohibited practices, GPAI provider obligations and penalties, transparency, Annex III high-risk systems, Annex I product-embedded systems.",
  "2 February 2025; 2 August 2025 (governance and penalties came with the GPAI rules); 2 August 2026 (transparency, market surveillance, Commission GPAI fines); 2 December 2027; 2 August 2028. The last two are the dates set by Regulation (EU) 2026/1744; the original Act said 2 August 2026 and 2 August 2027."),
 ("State the three penalty ceilings.",
  "Prohibited practices: 7% of global annual turnover or EUR 35m. Operator, notified-body and transparency obligations: 3% or EUR 15m (the same ceiling for GPAI providers under Article 101). Incorrect or misleading information to regulators: 1% or EUR 7.5m. Whichever is higher, except SMEs, startups and small mid-caps, where the lower amount applies."),
 ("Which of the ten governance foundations should be stood up first, and why?",
  "The live AI inventory. Most of the rest depends on knowing what you have, and shadow AI adoption is usually larger than leadership assumes."),
 ("Which three of the ten vendor questions belong in the contract rather than an email?",
  "IP indemnity, data-use rights (whether they train on your data), and output ownership."),
 ("Does Article 4 require a four-layer training programme?",
  "No. Article 4, as amended in 2026, requires measures that support the development of AI literacy, fitted to the people, the context and the risk; it prescribes no curriculum, level or certificate. The four layers are a design that produces that evidence, and layer four is what serves the separate Article 26(2) requirement that oversight staff for high-risk systems be competent and trained."),
 ("At which five points in the AI lifecycle does copyright exposure arise?",
  "Training, fine-tuning, retrieval-augmented generation, prompts and inputs, and inference and outputs."),
 ("Is AI output copyrightable?",
  "It depends on human authorship. Purely AI-generated content with no meaningful human creative input generally is not protectable in most jurisdictions; AI-assisted work often is. The dividing line is whether a human's own creative choices are perceptible in the result."),
]
