# -*- coding: utf-8 -*-
"""Builds the AI governance crosswalk page.

Inputs (beside this script):
  rows.py              the crosswalk rows (AI Act obligation -> ISO/IEC 42001 -> NIST AI RMF)
  nist_ai_rmf.json     NIST AI 100-1 functions, categories and subcategories, verbatim
  iso42001.json        ISO/IEC 42001 clause and Annex A titles, and the NIST-hosted
                       AI RMF to ISO/IEC 42001 crosswalk as printed
  ai_act_digest.json   the AI Act Digest data set, for article titles and dates

Outputs (into OUT, default ./out):
  ai-governance-crosswalk.html
  pages/ai-crosswalk/crosswalk-data.js
  (crosswalk.js and crosswalk.css are hand-written and copied as they are)

No em dashes anywhere. Run: python3 build_crosswalk.py [OUT]
"""
import json, os, sys, shutil, html, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out")
sys.path.insert(0, HERE)
import rows as R

nist = json.load(open(os.path.join(HERE, "nist_ai_rmf.json"), encoding="utf-8"))
iso = json.load(open(os.path.join(HERE, "iso42001.json"), encoding="utf-8"))
digest = json.load(open(os.path.join(HERE, "ai_act_digest.json"), encoding="utf-8"))["regulation"]
ART = {x["id"]: x for x in digest}

# ---------------------------------------------------------------- data ---
iso_items = []
for c in iso["clauses"]:
    iso_items.append({"id": c["id"], "title": c["title"], "kind": "clause", "group": c["id"].split(".")[0]})
GROUP_TITLES = {}
for g in iso["annex_a"]:
    GROUP_TITLES[g["group"]] = g["group_title"]
    for c in g["controls"]:
        iso_items.append({"id": c["id"], "title": c["title"], "kind": "control", "group": g["group"]})
CLAUSE_GROUPS = {
    "4": "Context of the organization", "5": "Leadership", "6": "Planning", "7": "Support",
    "8": "Operation", "9": "Performance evaluation", "10": "Improvement",
}
ISO_IDS = {x["id"] for x in iso_items}

nist_fns = []
NIST_IDS = set()
for f in nist["functions"]:
    cats = []
    for c in f["categories"]:
        subs = [{"id": s["id"], "text": s["text"]} for s in c["subcategories"]]
        NIST_IDS.update(s["id"] for s in subs)
        cats.append({"id": c["id"], "text": c["text"], "subs": subs})
    nist_fns.append({"id": f["id"], "cats": cats})

hosted = []
for r in iso["crosswalk"]["rows"]:
    equiv = [x for x in r.get("iso_annex_a_equiv", r["iso"]) if x in ISO_IDS or re.match(r"^A\.", x)]
    hosted.append({"nist": r["nist"], "printed": r["iso"], "equiv": r.get("iso_annex_a_equiv", r["iso"])})

def art_entry(aid):
    a = ART[aid]
    return {"id": aid, "label": a["number"], "title": a["title"], "from": a["applies_from"]}

rows_out = []
for r in R.ROWS:
    for x in r["iso"]:
        assert x in ISO_IDS, x
    for x in r["nist"]:
        assert x in NIST_IDS, x
    rows_out.append({
        "id": r["id"], "theme": r["theme"], "role": r["role"],
        "aia": [art_entry(a) for a in r["aia"]],
        "obligation": r["obligation"], "iso": r["iso"], "nist": r["nist"],
        "note": r.get("note", ""), "gap": r.get("gap", ""), "tool": r.get("tool", ""),
        "applies": r["applies"],
    })

data = {
    "themes": [{"id": t, "label": l} for t, l in R.THEMES],
    "roles": R.ROLES,
    "rows": rows_out,
    "iso": iso_items,
    "isoClauseGroups": CLAUSE_GROUPS,
    "isoAnnexGroups": GROUP_TITLES,
    "nist": nist_fns,
    "hosted": hosted,
    "hostedMeta": {
        "title": iso["crosswalk"].get("title", ""),
        "url": iso["crosswalk"].get("url", ""),
    },
}
blob = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
assert "\u2014" not in blob, "em dash in data"

# ---------------------------------------------------------------- page ---
def stats():
    n_rows = len(rows_out)
    iso_used = {x for r in rows_out for x in r["iso"]}
    nist_used = {x for r in rows_out for x in r["nist"]}
    return n_rows, len(iso_used), len(ISO_IDS), len(nist_used), len(NIST_IDS)

n_rows, iso_used, iso_total, nist_used, nist_total = stats()

TEMPLATE = open(os.path.join(HERE, "page_template.html"), encoding="utf-8").read()
page = (TEMPLATE
        .replace("@@N_ROWS@@", str(n_rows))
        .replace("@@ISO_USED@@", str(iso_used)).replace("@@ISO_TOTAL@@", str(iso_total))
        .replace("@@NIST_USED@@", str(nist_used)).replace("@@NIST_TOTAL@@", str(nist_total)))
assert "@@" not in page
assert "\u2014" not in page, "em dash in page"

os.makedirs(os.path.join(OUT, "pages", "ai-crosswalk"), exist_ok=True)
open(os.path.join(OUT, "ai-governance-crosswalk.html"), "w", encoding="utf-8", newline="\n").write(page)
open(os.path.join(OUT, "pages", "ai-crosswalk", "crosswalk-data.js"), "w", encoding="utf-8", newline="\n").write(
    "/* Generated by Claude outputs/ai-crosswalk-build/build_crosswalk.py. Do not edit by hand. */\n"
    "window.CW_DATA = " + blob + ";\n")
for f in ("crosswalk.js", "crosswalk.css"):
    src = open(os.path.join(HERE, f), encoding="utf-8").read()
    assert "\u2014" not in src, "em dash in " + f
    shutil.copy(os.path.join(HERE, f), os.path.join(OUT, "pages", "ai-crosswalk", f))
print("rows", n_rows, "| ISO", iso_used, "of", iso_total, "| NIST", nist_used, "of", nist_total)
print("written to", OUT)
