# -*- coding: utf-8 -*-
"""Crosswalk rows: one AI Act obligation per row, with the ISO/IEC 42001 clauses and Annex A
controls and the NIST AI RMF 1.0 subcategories that support it. The mapping is this site's
own reading, made by Claude for Simeon Atanasov on 3 October 2026 and checked against the
AI Act Digest takeaways, the NIST AI 100-1 text, and the NIST-hosted AI RMF to ISO/IEC 42001
crosswalk. Obligation text is a paraphrase, not the Regulation's wording."""

THEMES = [
    ("scope", "Scope, roles and literacy"),
    ("build", "Provider: building a high-risk system"),
    ("market", "Provider: placing on the market and after"),
    ("use", "Deployer: using a high-risk system"),
    ("transparency", "Transparency for certain AI systems"),
    ("gpai", "General-purpose AI models"),
]

HR = "When the high-risk rules apply: 2 December 2027 (Annex III), 2 August 2028 (Annex I)"

ROLES = {"both": "Provider and deployer", "provider": "Provider", "deployer": "Deployer", "gpai": "GPAI model provider"}

ROWS = [
 dict(id="r01", theme="scope", role="both", aia=["art-4"], applies="2 February 2025",
  obligation="For any AI system, not only high-risk ones, take measures to support AI literacy among staff and others who operate the systems on your behalf, taking account of their knowledge, the context of use and the people affected. No individual level has to be guaranteed.",
  iso=["7.2", "7.3", "A.4.6"], nist=["GOVERN 2.2", "MAP 3.4"],
  note="ISO/IEC 42001 asks for competence and awareness for roles in the AI management system; the AI Act duty reaches anyone operating the systems on your behalf, including contractors."),
 dict(id="r02", theme="scope", role="both", aia=["art-5"], applies="2 February 2025; the two new prohibitions from 2 December 2026",
  obligation="Screen every AI use against the prohibited practices before it is built or deployed, and stop any use that falls within them.",
  iso=["4.1", "6.1.4", "A.5.2", "A.9.4"], nist=["GOVERN 1.1", "MAP 1.1", "MANAGE 1.1"],
  note="Neither framework lists prohibited uses. ISO/IEC 42001 requires legal requirements to be determined and intended use to be defined, and NIST MANAGE 1.1 requires a decision on whether development or deployment should proceed; the list itself comes from Article 5, including the new bans on generating non-consensual intimate imagery and child sexual abuse material that apply from 2 December 2026.", gap="partial"),
 dict(id="r03", theme="scope", role="provider", aia=["art-6", "art-49"], applies=HR,
  obligation="Classify each system against the two high-risk routes: safety components of, or products under, Annex I legislation that require third-party conformity assessment, and the Annex III use cases. Where you rely on the Article 6(3) exception, which is never available for profiling of natural persons, document the assessment before placing the system on the market and register it (Article 6(4), Article 49(2)).",
  iso=["4.1", "4.3", "A.5.2"], nist=["GOVERN 1.1", "GOVERN 1.6", "MAP 1.1", "MAP 3.3"],
  note="An AI inventory (GOVERN 1.6) is where the classification is recorded. The registration duty has no equivalent in either framework.", gap="partial"),
 dict(id="r04", theme="scope", role="both", aia=["art-25"], applies=HR,
  obligation="Know when you become the provider: putting your name on a high-risk system, modifying a high-risk system substantially so that it remains high-risk, or changing a system's intended purpose so that it becomes high-risk. The initial provider must then supply technical documentation, known limitations and failure modes and technical access. Agree in writing what suppliers of tools, components and models provide.",
  iso=["4.1", "A.10.2", "A.10.3", "A.10.4", "A.9.4"], nist=["GOVERN 6.1", "MAP 4.1", "MANAGE 3.1"],
  note="ISO/IEC 42001 asks the organisation to determine its roles with respect to AI systems and to allocate responsibilities with its partners, but has no concept of the role switch in Article 25(1).", gap="partial"),

 dict(id="r05", theme="build", role="provider", aia=["art-9"], applies=HR,
  obligation="Run a documented risk management system for each high-risk system across its lifecycle: identify and estimate the risks to health, safety and fundamental rights under intended use and foreseeable misuse, evaluate post-market monitoring data, adopt measures until residual risk is acceptable, and test against predefined metrics before release.",
  iso=["6.1.1", "6.1.2", "6.1.3", "8.2", "8.3", "9.1", "A.6.2.4"], nist=["GOVERN 1.3", "GOVERN 1.4", "MAP 5.1", "MEASURE 1.1", "MEASURE 2.3", "MEASURE 2.6", "MANAGE 1.2", "MANAGE 1.3", "MANAGE 1.4"],
  note="ISO/IEC 42001 risk assessment runs at the level of the management system; Article 9 wants one per system, with specific attention to people under 18 and vulnerable groups (paragraph 9)."),
 dict(id="r06", theme="build", role="provider", aia=["art-10", "art-4a"], applies=HR,
  obligation="Govern training, validation and testing data: document design choices, origin, preparation and assumptions, check representativeness and errors, and examine and mitigate bias. Special-category data for bias detection only under the conditions of Article 4a.",
  iso=["A.4.3", "A.7.2", "A.7.3", "A.7.4", "A.7.5", "A.7.6"], nist=["MAP 2.3", "MEASURE 2.10", "MEASURE 2.11"],
  note="The data controls in Annex A are the closest match on this page. Neither framework gives a legal basis for processing special-category data; Article 4a and the GDPR do. Article 4a(2) extends the permission, under the same safeguards, to deployers of high-risk systems and to providers and deployers of other systems."),
 dict(id="r07", theme="build", role="provider", aia=["art-11", "art-18"], applies=HR,
  obligation="Draw up the Annex IV technical documentation before the system is placed on the market or put into service, keep it up to date, and keep it for ten years after that date.",
  iso=["7.5", "A.4.2", "A.6.2.3", "A.6.2.7"], nist=["GOVERN 4.2", "MAP 2.1", "MAP 2.2", "MEASURE 2.1"],
  note="Annex IV prescribes the content. Documented information under ISO/IEC 42001 is not structured to it, so a mapping exercise is still needed. SMEs, start-ups and small mid-caps may use the Commission's simplified form, which notified bodies must accept (Article 11(1) as amended).", gap="partial"),
 dict(id="r08", theme="build", role="provider", aia=["art-12", "art-19"], applies=HR,
  obligation="Design the system to log events automatically over its lifetime, so that risks and substantial modifications can be traced, and keep the logs under your control for a period appropriate to the intended purpose, at least six months unless Union or national law, in particular data protection law, provides otherwise.",
  iso=["A.6.2.8", "7.5.3"], nist=["MEASURE 2.4", "MEASURE 2.6", "MANAGE 4.1"],
  note="The six-month minimum is an AI Act figure; neither framework sets one. It is a floor, and data protection law can shorten or lengthen it."),
 dict(id="r09", theme="build", role="provider", aia=["art-13"], applies=HR,
  obligation="Make the system's operation transparent enough for deployers to interpret its output, and supply instructions for use with the content Article 13(3) lists, including accuracy levels, known risks, performance for specific groups and the oversight measures.",
  iso=["A.6.2.7", "A.8.2", "A.9.4"], nist=["MAP 2.2", "MEASURE 2.5", "MEASURE 2.8", "MEASURE 2.9", "MANAGE 1.4"],
  note=""),
 dict(id="r10", theme="build", role="provider", aia=["art-14"], applies=HR,
  obligation="Design the system so that people can oversee it in use, with measures proportionate to the risks and the level of autonomy, built in or specified for the deployer: understand its capacities and limits, stay aware of automation bias, interpret the output, decide not to use it, override it or stop it.",
  iso=["A.6.1.3", "A.6.2.2", "A.9.2"], nist=["GOVERN 3.2", "MAP 2.2", "MAP 3.5", "MANAGE 2.4"],
  note="ISO/IEC 42001 has no control named human oversight; it sits in the design requirements and the responsible-use processes. NIST names it directly in MAP 3.5 and GOVERN 3.2."),
 dict(id="r11", theme="build", role="provider", aia=["art-15", "art-42"], applies=HR,
  obligation="Achieve and declare an appropriate level of accuracy, robustness and cybersecurity throughout the lifecycle, including resilience against data and model poisoning, adversarial examples and confidentiality attacks.",
  iso=["A.6.2.2", "A.6.2.4"], nist=["MEASURE 2.3", "MEASURE 2.5", "MEASURE 2.6", "MEASURE 2.7"],
  note="The security controls themselves are outside ISO/IEC 42001; ISO/IEC 27001 is where they sit. Certification under a cybersecurity scheme cited in the Official Journal, or meeting the Cyber Resilience Act conditions, presumes or deems compliance with the cybersecurity part of Article 15 (Article 42(2) and (3))."),
 dict(id="r12", theme="build", role="provider", aia=["art-17"], applies=HR,
  obligation="Run a documented quality management system covering the thirteen areas of Article 17(1), from regulatory compliance strategy and design controls to post-market monitoring, incident reporting and an accountability framework.",
  iso=["4.4", "5.1", "5.2", "5.3", "6.2", "7.1", "7.5", "8.1", "9.2", "9.3", "10.1", "10.2"], nist=["GOVERN 1.1", "GOVERN 1.4", "GOVERN 1.5", "GOVERN 2.1", "GOVERN 2.3"],
  note="The widest overlap on the page: an AI management system covers much of the organisational frame of Article 17. Product-specific points such as conformity procedures, standards applied and communication with notified bodies are not covered. ISO/IEC 42001 is not cited as a harmonised standard under the AI Act, so certifying against it gives no presumption of conformity. EN 18286:2026, the quality management standard written for Article 17, was published in July 2026 and gives a presumption of conformity only once its reference is cited in the Official Journal; check the Official Journal before relying on it.", gap="partial"),

 dict(id="r13", theme="market", role="provider", aia=["art-43", "art-47", "art-48", "art-49", "art-22"], applies=HR,
  obligation="Complete the conformity assessment, draw up the EU declaration of conformity, affix the CE marking and register Annex III systems in the EU database before placing on the market. Repeat the assessment after a substantial modification, unless the change was pre-determined in the technical documentation (Article 43(4)). Providers established outside the Union first appoint an authorised representative in the Union by written mandate (Article 22).",
  iso=[], nist=[],
  note="No equivalent in either framework. These are product-law steps specific to the AI Act.", gap="none"),
 dict(id="r14", theme="market", role="provider", aia=["art-72"], applies=HR,
  obligation="Establish a post-market monitoring system and plan, part of the technical documentation, that collects and analyses performance data over the system's lifetime to confirm continued compliance.",
  iso=["9.1", "10.1", "A.6.2.6"], nist=["MEASURE 2.4", "MEASURE 3.1", "MANAGE 4.1", "MANAGE 4.2"],
  note=""),
 dict(id="r15", theme="market", role="provider", aia=["art-20", "art-73"], applies=HR,
  obligation="Take corrective action on non-conforming systems and inform the operators concerned. Report serious incidents to the market surveillance authority of the Member State where they occurred, immediately once a causal link is established or reasonably likely and at the latest 15 days after becoming aware; two days for a widespread infringement or a serious disruption of critical infrastructure, ten days for a death.",
  iso=["10.2", "A.8.3", "A.8.4"], nist=["GOVERN 4.3", "MANAGE 2.3", "MANAGE 2.4", "MANAGE 4.3"],
  note="Both frameworks require incident handling and communication. The recipients and the deadlines are the AI Act's own.", gap="partial"),

 dict(id="r27", theme="market", role="provider", aia=["art-16", "art-21"], applies=HR,
  obligation="Mark the system or its packaging with your name and contact address, meet the accessibility requirements of Directives (EU) 2016/2102 and 2019/882, and on reasoned request give the authorities the information, documentation and log access needed to demonstrate conformity (Article 16(b), (k) and (l), Article 21).",
  iso=["7.5.3", "A.8.3"], nist=["GOVERN 1.1", "GOVERN 4.3"],
  note="Marking and accessibility have no equivalent in either framework; documentation control and external reporting support the cooperation duty.", gap="partial"),

 dict(id="r16", theme="use", role="deployer", aia=["art-26"], applies=HR,
  obligation="Use the system in line with the provider's instructions for use and assign human oversight to people with the competence, training and authority to exercise it (Article 26(1) and (2)).",
  iso=["7.2", "A.3.2", "A.9.2", "A.9.4"], nist=["GOVERN 2.1", "GOVERN 3.2", "MAP 3.4", "MAP 3.5"],
  note=""),
 dict(id="r17", theme="use", role="deployer", aia=["art-26"], applies=HR,
  obligation="Where you control the input data, make sure it is relevant and sufficiently representative for the intended purpose (Article 26(4)).",
  iso=["A.7.4", "A.7.6"], nist=["MAP 2.3"],
  note=""),
 dict(id="r18", theme="use", role="deployer", aia=["art-26"], applies=HR,
  obligation="Monitor operation, inform the provider and the authority and suspend use where the system presents a risk, report serious incidents, and keep the logs under your control for a period appropriate to the intended purpose, at least six months unless other Union or national law, in particular data protection law, provides otherwise (Article 26(5) and (6)).",
  iso=["A.6.2.6", "A.6.2.8", "A.8.4", "A.10.3"], nist=["GOVERN 6.2", "MEASURE 2.4", "MANAGE 2.4", "MANAGE 4.1", "MANAGE 4.3"],
  note="ISO/IEC 42001 treats the provider as a supplier (A.10.3). The duty to suspend and to tell the authority is the AI Act's own."),
 dict(id="r19", theme="use", role="deployer", aia=["art-26"], applies=HR,
  obligation="Inform workers' representatives and affected workers before using a high-risk system at work, and tell people that an Annex III high-risk system is used in decisions about them (Article 26(7) and (11)).",
  iso=["7.4", "A.8.5"], nist=["GOVERN 4.2", "GOVERN 5.1"],
  note="Neither framework requires notice to workers or affected persons; the duty is the AI Act's own. Communication with interested parties is the nearest match.", gap="partial"),
 dict(id="r20", theme="use", role="deployer", aia=["art-26", "art-49"], applies=HR,
  obligation="Public authorities and Union bodies register themselves and their use of an Annex III system (other than critical infrastructure) in the EU database before use, and do not use a system the provider has not registered, informing the provider or distributor instead (Article 26(8), Article 49(3)).",
  iso=[], nist=[],
  note="No equivalent in either framework.", gap="none"),
 dict(id="r21", theme="use", role="deployer", aia=["art-27"], applies=HR,
  obligation="Bodies governed by public law, private operators providing public services, and deployers of Annex III credit scoring and life and health insurance pricing systems carry out a fundamental rights impact assessment before first use of an Annex III system (other than critical infrastructure). It covers the process, period and frequency of use, the people affected, the risks of harm, the oversight measures, and the measures if risks materialise, including governance and complaint arrangements. Notify the market surveillance authority of the results and update the assessment when elements change.",
  iso=["6.1.4", "8.4", "A.5.2", "A.5.3", "A.5.4", "A.5.5"], nist=["GOVERN 5.1", "MAP 1.1", "MAP 5.1", "MAP 5.2", "MEASURE 2.11", "MEASURE 3.3"],
  note="The AI system impact assessment of ISO/IEC 42001, with ISO/IEC 42005 as its guidance, is the closest match. Notification to the authority has no equivalent. Article 27(4), as amended, lets the FRIA cross-refer to or incorporate a GDPR DPIA.", gap="partial", tool="fria"),
 dict(id="r22", theme="use", role="deployer", aia=["art-86"], applies=HR,
  obligation="Where a decision based on the output of an Annex III high-risk system (other than critical infrastructure) has legal or similarly significant effects that the affected person considers adverse to their health, safety or fundamental rights, give that person, on request, a clear and meaningful explanation of the role the system played and of the main elements of the decision.",
  iso=["A.8.2", "A.8.5"], nist=["MEASURE 2.9", "MEASURE 3.3"],
  note="Article 86 applies only where Union law does not already give the right (paragraph 3). For solely automated decisions under Article 22 GDPR, the explanation right in Article 15(1)(h) GDPR comes first, and Article 86 covers the remaining cases, such as decisions where a human is involved."),

 dict(id="r23", theme="transparency", role="provider", aia=["art-50", "art-111"], applies="2 August 2026; generators already on the market before then by 2 December 2026",
  obligation="Design systems that interact with people so that they know they are dealing with AI, unless that is obvious, and mark synthetic audio, image, video and text output in a machine-readable, detectable way as far as technically feasible (Article 50(1) and (2)).",
  iso=["A.6.2.2", "A.8.2"], nist=["GOVERN 1.1", "MEASURE 2.8"],
  note="AI RMF 1.0 has no disclosure or marking outcome; the duty is the AI Act's own. Providers of generators already on the market before 2 August 2026 have until 2 December 2026 to meet Article 50(2) (Article 111(4)). The Commission has assessed the transparency Code of Practice as adequate for Article 50(2), (4) and (5): a recognised route, though not conclusive evidence. NIST AI 600-1 treats content provenance under its information integrity risk.", gap="partial", tool="genai"),
 dict(id="r24", theme="transparency", role="deployer", aia=["art-50"], applies="2 August 2026",
  obligation="Inform people exposed to emotion recognition or biometric categorisation, and disclose deep fakes and AI-generated text published on matters of public interest, clearly and at the latest at the first interaction or exposure (Article 50(3) to (5)).",
  iso=["7.4", "A.8.5", "A.9.2"], nist=["GOVERN 1.1", "MEASURE 2.8"],
  note="AI RMF 1.0 has no disclosure or labelling outcome; the duty is the AI Act's own. Section 2 of the transparency Code of Practice is the recognised way to meet Article 50(4). The exceptions for artistic works and text under editorial responsibility apply.", gap="partial"),

 dict(id="r25", theme="gpai", role="gpai", aia=["art-53", "art-54"], applies="2 August 2025; models on the market before then by 2 August 2027",
  obligation="Keep Annex XI technical documentation, give downstream providers the Annex XII information, adopt a copyright policy that respects rights reservations, and publish a summary of training content.",
  iso=["A.6.2.7", "A.7.5", "A.8.2"], nist=["GOVERN 6.1", "MAP 2.2", "MAP 4.1"],
  note="ISO/IEC 42001 was not written for model providers. The copyright policy and the public training summary are the AI Act's own. The GPAI Code of Practice, assessed as adequate by the Commission and the AI Board, is a recognised way to show compliance; non-signatories show adequate alternative means. Free and open-source models with public weights are exempt from the two documentation duties unless they carry systemic risk. Providers outside the Union appoint an authorised representative (Article 54).", gap="partial"),
 dict(id="r26", theme="gpai", role="gpai", aia=["art-55"], applies="2 August 2025; models on the market before then by 2 August 2027",
  obligation="For models with systemic risk: evaluate the model with standardised protocols including adversarial testing, assess and mitigate systemic risks at Union level, track, document and report serious incidents and corrective measures to the AI Office and, where relevant, national authorities without undue delay, and secure the model and its infrastructure.",
  iso=["6.1.2", "A.6.2.4", "A.8.4"], nist=["MAP 5.1", "MEASURE 1.3", "MEASURE 2.6", "MEASURE 2.7", "MANAGE 4.3"],
  note="The Safety and Security chapter of the GPAI Code of Practice is the recognised route for Article 55. NIST AI 600-1, the Generative AI Profile, adds generative-specific actions to these subcategories.", tool="genai"),

 dict(id="r28", theme="gpai", role="gpai", aia=["art-51", "art-52"], applies="2 August 2025",
  obligation="Track the cumulative training compute of each model and notify the Commission within two weeks once a model meets, or is known to be going to meet, the systemic-risk threshold (Article 51, Article 52(1)).",
  iso=[], nist=["GOVERN 1.1"],
  note="No equivalent in either framework beyond knowing the legal requirements.", gap="none"),
]
