# -*- coding: utf-8 -*-
"""One-line descriptions for the 115 not-relevant documents of substantive type,
keyed by inventory index. Written from title and known content; British spelling,
no em dashes."""

MANUAL = {
 0: "A model agreement for cooperation between data protection authorities and other regulators (competition, consumer, digital services). For authorities, not controllers.",
 3: "Final guidelines on blockchain: a public permissionless chain makes erasure and rectification hard to honour, so store personal data off-chain where possible and run a DPIA before any on-chain personal data. Version 2.0, 8 July 2026. Outside the site's topics.",
 6: "Article 65 decision on whether a complaint against the Flemish broadcaster VRT should be dismissed as an abuse of the right to complain and to mandate a not-for-profit body. Procedural: it settles when authorities may reject complaints, not any substantive processing question.",
 10: "Comments to the Commission on the interim measures specifying Alphabet's obligations under the Digital Markets Act, mainly on data portability and combining data across services. Gatekeeper platforms only.",
 15: "Administrative report on how the Board's external expert pool was used during 2025.",
 23: "Joint EDPB-EDPS opinion on the proposed European Biotech Act, on the handling of genetic and health data in research and regulatory pathways. Sector legislation.",
 24: "Letter to the Commission on the privacy implications of proposed changes to entry conditions for third-country nationals (border and travel data). Border management only.",
 30: "Reply to civil society on spyware abuse: the Board restates that surveillance tools used against journalists and activists engage fundamental rights and calls for enforcement of existing safeguards. Law enforcement and national security.",
 40: "Report on cooperation between data protection enforcement bodies internationally: mechanisms, obstacles and recommendations for authorities.",
 44: "Template form for an EU resident to complain to a national authority about a US company certified under the Data Privacy Framework. Useful to individuals; controllers need only know it exists.",
 47: "The Board's contribution to the Commission's evaluation of the Law Enforcement Directive. Police and justice sector.",
 57: "Expert report on the privacy design of the digital euro's offline, token-based mode. Payments sector.",
 69: "Comments to the European Banking Authority on draft technical standards for anti-money-laundering controls, on data minimisation and retention in customer due diligence. Financial sector.",
 72: "Statement on the Commission's model contractual terms for data sharing under the Data Act: the terms must not be read as a lawful basis, and personal data in shared datasets still needs its own GDPR footing.",
 76: "The Helsinki Statement (April 2025): the Board commits to plainer guidance, more support for small organisations and closer engagement with stakeholders. Programme statement, no obligations.",
 77: "Comments on the Commission's Digital Services Act Article 28 guidelines on protecting minors online, on age assurance and profiling-based advertising to children. Platforms in scope of the DSA.",
 95: "Administrative report on how the Board's external expert pool was used during 2024.",
 97: "Statement on how Member States should implement the Passenger Name Record Directive after the Court of Justice's judgment in C-817/19: no general and indiscriminate retention. Air travel and law enforcement.",
 98: "Recommendations on the 2027 World Anti-Doping Code and its international standards, on the proportionality of athlete data processing and transfers. Sport governing bodies.",
 107: "Statement welcoming the Commission's second report on the GDPR and calling for consistency between the GDPR and newer digital laws. Policy position, no obligations.",
 113: "Statement on the High-Level Group's recommendations on law enforcement access to data, warning against weakening encryption and data retention mandates. Law enforcement policy.",
 114: "Report on the first periodic review of the EU-US Data Privacy Framework adequacy decision: the Board finds the safeguards in place but asks the Commission to keep monitoring the Data Protection Review Court and the PCLOB, and recommends the next review within three years. Transfers background.",
 117: "Statement on the draft Regulation laying down additional procedural rules for cross-border GDPR enforcement, supporting harmonised deadlines and parties' rights. Now adopted as Regulation (EU) 2025/2518.",
 130: "Administrative report on how the Board's external expert pool was used in its first period.",
 134: "Expert methodology for auditing messaging services against data protection requirements, for supervisory authorities.",
 135: "Guidelines on Article 37 of the Law Enforcement Directive: transfers by police and judicial authorities to third countries on the basis of appropriate safeguards. Police and justice sector.",
 140: "Statement on the financial data access and payments package (FIDA, PSD3, PSR), asking for clear purpose limits and consent rules for open finance data sharing. Financial sector.",
 153: "Report on enforcing the GDPR against organisations outside the EEA that fall under Article 3(2), covering representatives, service of decisions and international cooperation. For authorities.",
 155: "Statement on the proposed Regulation to prevent and combat child sexual abuse, warning that general and indiscriminate scanning of private communications is disproportionate. Legislative position.",
 169: "The Board's 2023 input to the Commission's report on the application of the GDPR: cooperation, resources and areas needing clarification.",
 187: "Joint opinion on the proposed Regulation establishing a framework for a European Digital Identity wallet (eIDAS 2). Identity infrastructure.",
 191: "Joint contribution on the Commission's template for describing consumer profiling techniques under the Digital Markets Act. Gatekeepers only.",
 192: "Joint opinion on the proposed Regulation laying down additional procedural rules for cross-border GDPR enforcement, supporting the aim and asking for clearer time limits and parties' rights.",
 197: "Statement on the first review of the Japan adequacy decision: the Board sees no need to change it and asks for continued monitoring of onward transfers and government access. Transfers background.",
 202: "Template complaint form and template acknowledgement of receipt for use by supervisory authorities, to harmonise how complaints are lodged across the EEA.",
 204: "Guidelines on when the Board may adopt a binding decision under Article 65(1)(a) after a relevant and reasoned objection. Procedure between authorities.",
 206: "Guidelines on facial recognition technology in law enforcement: necessity and proportionality, prohibited uses such as remote identification in public and inference of protected characteristics, and the safeguards the Law Enforcement Directive requires. Police sector.",
 214: "External study on national administrative law rules that slow cooperation between supervisory authorities. Institutional.",
 215: "External study on enforcing GDPR obligations against controllers established outside the EEA under Article 3(2). For authorities.",
 225: "Guidelines on certification as a transfer tool under Article 46(2)(f): what a certification scheme must contain for a third-country importer to rely on it. No scheme has yet been approved for this use.",
 232: "Coordinated enforcement action on public bodies' use of cloud services: findings on DPIAs, contracts, transfers and the difficulty of negotiating with large providers. Public sector.",
 233: "Statement on the Court of Justice's PNR judgment (C-817/19) and its consequences for national implementation. Air travel and law enforcement.",
 241: "Statement on privacy design choices for a digital euro, asking for a high privacy threshold for offline payments. Payments sector.",
 246: "Statement on the proposed European Police Cooperation Code (Prüm II and information exchange). Police sector.",
 250: "Survey of the staff and budget Member States give their data protection authorities, and the gaps. Institutional.",
 257: "Joint opinion on the proposed Regulation on rules to prevent and combat child sexual abuse, finding the detection orders disproportionate. Legislative position.",
 258: "Article 65 decision in the Irish authority's Meta (Facebook) inquiry into the 2019 data scraping incident, directing the final fine and findings on Article 25 data protection by design. Enforcement history; the substantive point on default settings is in Article 25 guidance.",
 259: "Statement on transfers to the Russian Federation after the invasion of Ukraine: exporters must reassess transfer impact assessments in light of the legal situation there. Transfers.",
 260: "Joint opinion on the proposed European Health Data Space Regulation, on secondary use of health data and patients' opt-out. Health sector.",
 268: "Article 65 decision on the French authority's Accor case, adjusting the fine for direct marketing without valid consent and access request failures. Enforcement history.",
 269: "Response to the Commission's targeted consultation on the digital euro. Payments sector.",
 270: "Guidelines on how supervisory authorities may settle cross-border complaints amicably under Article 60. Procedure between authorities.",
 272: "Joint opinion on the proposed Data Act, on the interplay between data access rights for connected products and the GDPR. Now adopted; the point that personal data in product data keeps its GDPR footing stands.",
 275: "Statement committing authorities to closer cooperation on strategic cross-border cases. Institutional.",
 282: "Joint opinion on extending the Covid-19 certificate Regulation. Historical.",
 283: "Guidelines on the cooperation procedure between lead and concerned authorities under Article 60. Procedure between authorities.",
 284: "Toolbox of safeguards for sharing information between data protection authorities and other regulators (competition, consumer). For authorities.",
 285: "Guidelines on codes of conduct as a transfer tool under Article 46(2)(e): what a code must contain for a third-country importer to rely on it. No code has yet been approved for this use.",
 286: "Call for experts to join the Board's Support Pool of Experts. Administrative.",
 292: "The Board's 2021 contribution to the Commission's evaluation of the Law Enforcement Directive. Police and justice sector.",
 301: "Guidelines on Article 23: Member State laws restricting data subject rights must be necessary, proportionate, foreseeable and time-limited, and cannot suspend rights wholesale. Relevant to legislators and public bodies.",
 303: "External study on the safeguards Article 89(1) requires for scientific research processing. Research sector.",
 304: "Survey of authority resources and enforcement actions across Member States. Institutional.",
 311: "External study on the interplay between anti-money-laundering rules and the GDPR. Financial sector.",
 316: "Urgent binding decision refusing the Hamburg authority's request for final measures against Facebook over WhatsApp data sharing, while asking the Irish authority to investigate. Procedural precedent on Article 66 urgency.",
 322: "Leaflet explaining the one-stop-shop mechanism to the public.",
 325: "Opinion on the EU tobacco traceability system's processing of personal data. Sector legislation.",
 329: "Statement on the Data Governance Act as negotiated, asking that data intermediation and altruism stay consistent with the GDPR. Now adopted.",
 334: "Contribution on the draft Second Additional Protocol to the Budapest Convention on Cybercrime, on direct cross-border access to data by law enforcement. Law enforcement.",
 340: "Joint opinion on the proposed Regulation on a framework for a European Digital Identity. Identity infrastructure.",
 346: "Joint opinion on the proposed Data Governance Act. Now adopted.",
 348: "Guidelines on what makes an objection by a concerned authority relevant and reasoned under Article 4(24). Procedure between authorities.",
 355: "Recommendations on the adequacy referential under the Law Enforcement Directive: what the Commission assesses before finding a third country adequate for police transfers. Police sector.",
 357: "Response to the Commission's request for clarification on the consistent application of the GDPR to health research. Research sector.",
 358: "Statement on new draft provisions of the Budapest Convention's second protocol. Law enforcement.",
 366: "Update on the end of the Brexit transition period: the UK became a third country and the bridging period applied until adequacy was adopted. Historical.",
 373: "Guidelines on the interplay between the Second Payment Services Directive and the GDPR: explicit consent under PSD2 is contractual, not GDPR consent, and silent party data has limits. Payments sector.",
 374: "Statement on anti-money-laundering processing: know-your-customer duties must stay proportionate and must not become a general surveillance basis. Financial sector.",
 375: "Guidelines on transfers between EEA and non-EEA public bodies under Article 46(2)(a) and 46(3)(b): what a legally binding instrument or administrative arrangement must contain. Public bodies.",
 376: "Statement on the end of the Brexit transition period. Historical; see the UK adequacy decisions.",
 378: "Terms of reference of the Board's Support Pool of Experts. Administrative.",
 385: "Statement on the ePrivacy Regulation proposal and the future role of supervisory authorities. The proposal was withdrawn in February 2025.",
 387: "Frequently asked questions on the Article 65 dispute resolution procedure. Procedure between authorities.",
 389: "The Board's first Article 65 decision, on the Irish authority's Twitter breach notification case, directing a higher fine. Enforcement history; the substantive point on the 72-hour clock is in Guidelines 9/2022.",
 391: "Founding document of the Coordinated Enforcement Framework: how authorities pick and run an annual joint action. Institutional.",
 393: "External study on big data applications in European insurance and their data protection risks. Insurance sector background.",
 404: "Information note for groups whose binding corporate rules had the UK ICO as lead authority: how to move the lead to an EEA authority after Brexit. Historical.",
 408: "Statement on the interoperability of Covid-19 contact tracing apps. Historical.",
 409: "Statement on processing personal data when reopening borders after the Covid-19 outbreak. Historical.",
 410: "Statement on Member States restricting data subject rights during the Covid-19 state of emergency: restrictions must meet Article 23 and stay temporary. Historical.",
 422: "Guidelines on location data and contact tracing tools during the Covid-19 outbreak: voluntary use, no location tracking of individuals, proximity data only. Historical.",
 423: "Guidelines on processing health data for Covid-19 research: lawful bases, consent as a safeguard rather than a basis, transfers under Article 49. Historical; the general points are in the 2026 scientific research guidelines.",
 428: "Statement that the GDPR does not stand in the way of measures against Covid-19 and sets out the lawful bases employers and authorities can use. Historical.",
 429: "Reply to a letter from a member of the European Parliament on facial recognition. Correspondence.",
 430: "Statement that mergers of data-rich companies raise data protection issues and that authorities should be consulted in merger control. Policy position.",
 431: "The Board's 2020 contribution to the Commission's first evaluation of the GDPR. Institutional.",
 445: "Contribution to the consultation on the Budapest Convention's second protocol. Law enforcement.",
 448: "Third annual joint review of the EU-US Privacy Shield (2019). The framework was invalidated in July 2020; historical.",
 455: "The Board's pleading before the Court of Justice in Schrems II (C-311/18). Historical; the consequences are in Recommendations 01/2020.",
 464: "Joint opinion on patients' data and the Commission's role in the eHealth Digital Service Infrastructure. Health sector.",
 465: "Recommendation on the European Data Protection Supervisor's list of processing operations requiring a DPIA for EU institutions. EU institutions only.",
 466: "Guidelines on certification under Articles 42 and 43: how certification criteria are drafted and what a scheme must cover. For scheme owners and certification bodies.",
 467: "Guidelines on codes of conduct and monitoring bodies under Articles 40 and 41: how a code is drafted, approved and monitored. For code owners and sector associations.",
 470: "General leaflet introducing the Board.",
 471: "Statement urging the co-legislators to adopt the ePrivacy Regulation. The proposal was withdrawn in February 2025.",
 476: "Report to the European Parliament's LIBE committee on the first year of GDPR implementation. Institutional.",
 477: "Statement on the US Foreign Account Tax Compliance Act and the data protection issues in transferring account data to the US tax authority. Financial sector.",
 478: "Information note for companies whose binding corporate rules had the UK ICO as lead authority. Historical, superseded by the 2020 note.",
 479: "Information note on transfers to the UK in the event of a no-deal Brexit. Historical.",
 483: "Opinion on the Commission's questions and answers on the interplay between the Clinical Trials Regulation and the GDPR: consent to participate in a trial is not the GDPR lawful basis. Clinical research sector.",
 485: "Second annual joint review of the EU-US Privacy Shield (2019). Historical.",
 487: "Guidelines on accrediting certification bodies under Article 43, with Annex 1 setting the additional requirements beyond ISO/IEC 17065. For accreditation bodies and certification bodies.",
 516: "Opinion on the proposed e-evidence Regulation on cross-border production and preservation orders for electronic evidence. Law enforcement.",
 517: "Statement that economic concentration in data-driven markets has data protection impacts that competition review should take into account. Policy position.",
 525: "Statement on the revision of the ePrivacy Regulation proposal. The proposal was withdrawn in February 2025.",
}
